import 'color_token.dart';

// GENERATED by tool/generate_palette.py from tool/palette_tokens.py.
// Edit those and rerun instead of changing the token lists by hand.

/// The 48 tokens of a themeflow palette.
///
/// Read them with `context.palette.surface` and the like. Use this enum to
/// loop over tokens, or to look one up with `palette[PaletteToken.surface]`.
enum PaletteToken {
  /// Main brand color: filled buttons, selection and active states.
  primary(TokenRole.accent, 'Brand'),

  /// Text and icons on [primary].
  onPrimary(TokenRole.onColor, 'Brand'),

  /// A soft tint of [primary] for chips, badges and selected backgrounds.
  primaryContainer(TokenRole.container, 'Brand'),

  /// Text and icons on [primaryContainer].
  onPrimaryContainer(TokenRole.onColor, 'Brand'),

  /// A quieter companion to [primary].
  secondary(TokenRole.accent, 'Brand'),

  /// Text and icons on [secondary].
  onSecondary(TokenRole.onColor, 'Brand'),

  /// A soft tint of [secondary].
  secondaryContainer(TokenRole.container, 'Brand'),

  /// Text and icons on [secondaryContainer].
  onSecondaryContainer(TokenRole.onColor, 'Brand'),

  /// A contrasting accent.
  tertiary(TokenRole.accent, 'Brand'),

  /// Text and icons on [tertiary].
  onTertiary(TokenRole.onColor, 'Brand'),

  /// A soft tint of [tertiary].
  tertiaryContainer(TokenRole.container, 'Brand'),

  /// Text and icons on [tertiaryContainer].
  onTertiaryContainer(TokenRole.onColor, 'Brand'),

  /// The screen background (the scaffold).
  background(TokenRole.surface, 'Surfaces'),

  /// Cards, sheets and list rows.
  surface(TokenRole.surface, 'Surfaces'),

  /// Dialogs, menus and popovers.
  surfaceElevated(TokenRole.surface, 'Surfaces'),

  /// Filled inputs, search bars and chips.
  fill(TokenRole.surface, 'Surfaces'),

  /// Snackbars and tooltips: a surface in the opposite brightness.
  inverseSurface(TokenRole.surface, 'Surfaces'),

  /// Text and icons on [inverseSurface].
  onInverseSurface(TokenRole.onColor, 'Surfaces'),

  /// Body text and primary icons.
  text(TokenRole.content, 'Content'),

  /// Subtitles and secondary icons.
  textSecondary(TokenRole.content, 'Content'),

  /// Hints, timestamps and placeholders. Use it for non-essential text only.
  textTertiary(TokenRole.content, 'Content'),

  /// Disabled labels and icons.
  textDisabled(TokenRole.content, 'Content'),

  /// Inline links.
  link(TokenRole.accent, 'Content'),

  /// Input borders, outlined buttons and checkboxes.
  border(TokenRole.outline, 'Lines'),

  /// Dividers and hairlines.
  divider(TokenRole.outline, 'Lines'),

  /// Focus rings.
  focus(TokenRole.accent, 'Lines'),

  /// Errors.
  error(TokenRole.accent, 'Status'),

  /// Text and icons on [error].
  onError(TokenRole.onColor, 'Status'),

  /// A soft background for error messages.
  errorContainer(TokenRole.container, 'Status'),

  /// Text and icons on [errorContainer].
  onErrorContainer(TokenRole.onColor, 'Status'),

  /// Success and confirmations.
  success(TokenRole.accent, 'Status'),

  /// Text and icons on [success].
  onSuccess(TokenRole.onColor, 'Status'),

  /// A soft background for success messages.
  successContainer(TokenRole.container, 'Status'),

  /// Text and icons on [successContainer].
  onSuccessContainer(TokenRole.onColor, 'Status'),

  /// Warnings.
  warning(TokenRole.accent, 'Status'),

  /// Text and icons on [warning].
  onWarning(TokenRole.onColor, 'Status'),

  /// A soft background for warnings.
  warningContainer(TokenRole.container, 'Status'),

  /// Text and icons on [warningContainer].
  onWarningContainer(TokenRole.onColor, 'Status'),

  /// Neutral information.
  info(TokenRole.accent, 'Status'),

  /// Text and icons on [info].
  onInfo(TokenRole.onColor, 'Status'),

  /// A soft background for information messages.
  infoContainer(TokenRole.container, 'Status'),

  /// Text and icons on [infoContainer].
  onInfoContainer(TokenRole.onColor, 'Status'),

  /// The pressed and hover tint for custom widgets.
  overlay(TokenRole.content, 'Effects'),

  /// The text selection highlight.
  selection(TokenRole.accent, 'Effects'),

  /// Loading placeholders.
  skeleton(TokenRole.surface, 'Effects'),

  /// The moving highlight of a [skeleton] shimmer.
  skeletonHighlight(TokenRole.surface, 'Effects'),

  /// Modal barriers behind dialogs and sheets.
  scrim(TokenRole.fixed, 'Effects'),

  /// Shadows.
  shadow(TokenRole.fixed, 'Effects');

  const PaletteToken(this.role, this.group);

  /// What the token is for.
  final TokenRole role;

  /// The token's group: Brand, Surfaces, Content, Lines, Status or Effects.
  final String group;
}
