import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'color_token.dart';
import 'contrast_report.dart';
import 'dark_style.dart';
import 'derive.dart' show deriveCustomToken;
import 'palette_scope.dart';
import 'palette_token.dart';

// GENERATED by tool/generate_palette.py from tool/palette_tokens.py.
// Edit those and rerun instead of changing the token lists by hand.

/// Every token of a palette with a concrete value, for one brightness.
///
/// themeflow puts this in your `ThemeData` as a [ThemeExtension]. That way it
/// switches with the theme, animates with it, and reaches dialogs and sheets.
/// Read it with `context.palette` or [ResolvedPalette.of].
@immutable
class ResolvedPalette extends ThemeExtension<ResolvedPalette>
    with Diagnosticable {
  /// Creates a palette with every token set explicitly.
  ///
  /// Most apps never call this. `ThemeFlow` and [resolvePalettes] build
  /// palettes from a `ThemePalette`.
  factory ResolvedPalette({
    required Brightness brightness,
    required Color primary,
    required Color onPrimary,
    required Color primaryContainer,
    required Color onPrimaryContainer,
    required Color secondary,
    required Color onSecondary,
    required Color secondaryContainer,
    required Color onSecondaryContainer,
    required Color tertiary,
    required Color onTertiary,
    required Color tertiaryContainer,
    required Color onTertiaryContainer,
    required Color background,
    required Color surface,
    required Color surfaceElevated,
    required Color fill,
    required Color inverseSurface,
    required Color onInverseSurface,
    required Color text,
    required Color textSecondary,
    required Color textTertiary,
    required Color textDisabled,
    required Color link,
    required Color border,
    required Color divider,
    required Color focus,
    required Color error,
    required Color onError,
    required Color errorContainer,
    required Color onErrorContainer,
    required Color success,
    required Color onSuccess,
    required Color successContainer,
    required Color onSuccessContainer,
    required Color warning,
    required Color onWarning,
    required Color warningContainer,
    required Color onWarningContainer,
    required Color info,
    required Color onInfo,
    required Color infoContainer,
    required Color onInfoContainer,
    required Color overlay,
    required Color selection,
    required Color skeleton,
    required Color skeletonHighlight,
    required Color scrim,
    required Color shadow,
    DarkStyle style = const DarkStyle(),
  }) => ResolvedPalette.fromList(brightness, [
    primary,
    onPrimary,
    primaryContainer,
    onPrimaryContainer,
    secondary,
    onSecondary,
    secondaryContainer,
    onSecondaryContainer,
    tertiary,
    onTertiary,
    tertiaryContainer,
    onTertiaryContainer,
    background,
    surface,
    surfaceElevated,
    fill,
    inverseSurface,
    onInverseSurface,
    text,
    textSecondary,
    textTertiary,
    textDisabled,
    link,
    border,
    divider,
    focus,
    error,
    onError,
    errorContainer,
    onErrorContainer,
    success,
    onSuccess,
    successContainer,
    onSuccessContainer,
    warning,
    onWarning,
    warningContainer,
    onWarningContainer,
    info,
    onInfo,
    infoContainer,
    onInfoContainer,
    overlay,
    selection,
    skeleton,
    skeletonHighlight,
    scrim,
    shadow,
  ], style: style);

  /// Creates a palette from [colors], in [PaletteToken.values] order.
  ResolvedPalette.fromList(
    this.brightness,
    List<Color> colors, {
    this.style = const DarkStyle(),
    Map<String, Color> tokens = const {},
  }) : assert(colors.length == _count, 'Expected $_count colors.'),
       _colors = List<Color>.unmodifiable(colors),
       _tokens = Map<String, Color>.unmodifiable(tokens),
       _lerpFrom = null,
       _lerpTo = null,
       _t = 0;

  ResolvedPalette._lerped(
    this.brightness,
    List<Color> colors,
    this.style,
    ResolvedPalette from,
    ResolvedPalette to,
    double t,
  ) : _colors = List<Color>.unmodifiable(colors),
      _tokens = const {},
      _lerpFrom = from,
      _lerpTo = to,
      _t = t;

  static final int _count = PaletteToken.values.length;

  /// Light or dark.
  final Brightness brightness;

  /// The style dark colors were derived with. Custom tokens use it too.
  final DarkStyle style;

  final List<Color> _colors;
  final Map<String, Color> _tokens;
  final ResolvedPalette? _lerpFrom;
  final ResolvedPalette? _lerpTo;
  final double _t;

  // Memo of derived custom tokens. It only ever caches a pure function of
  // this palette, so the palette stays immutable in every observable way.
  final Map<ColorToken, Color> _derived = <ColorToken, Color>{};

  /// The nearest palette: from the current `Theme`, else from `ThemeFlow`.
  ///
  /// Widgets that call this rebuild when the theme changes.
  static ResolvedPalette of(BuildContext context) {
    final palette = maybeOf(context);
    if (palette != null) return palette;
    throw FlutterError.fromParts(<DiagnosticsNode>[
      ErrorSummary('No themeflow palette found in this context.'),
      ErrorHint(
        'Pass t.light and t.dark from ThemeFlow\'s builder to your '
        'MaterialApp (theme: t.light, darkTheme: t.dark), or put the app '
        'inside a ThemeFlow widget.',
      ),
    ]);
  }

  /// Like [of], but returns null when there's no palette.
  static ResolvedPalette? maybeOf(BuildContext context) =>
      Theme.of(context).extension<ResolvedPalette>() ??
      PaletteScope.maybeOf(context);

  /// The value of [token].
  Color operator [](PaletteToken token) => _colors[token.index];

  /// Every token's value, in [PaletteToken.values] order.
  List<Color> get colors => _colors;

  /// Main brand color: filled buttons, selection and active states.
  Color get primary => _colors[0];

  /// Text and icons on [primary].
  Color get onPrimary => _colors[1];

  /// A soft tint of [primary] for chips, badges and selected backgrounds.
  Color get primaryContainer => _colors[2];

  /// Text and icons on [primaryContainer].
  Color get onPrimaryContainer => _colors[3];

  /// A quieter companion to [primary].
  Color get secondary => _colors[4];

  /// Text and icons on [secondary].
  Color get onSecondary => _colors[5];

  /// A soft tint of [secondary].
  Color get secondaryContainer => _colors[6];

  /// Text and icons on [secondaryContainer].
  Color get onSecondaryContainer => _colors[7];

  /// A contrasting accent.
  Color get tertiary => _colors[8];

  /// Text and icons on [tertiary].
  Color get onTertiary => _colors[9];

  /// A soft tint of [tertiary].
  Color get tertiaryContainer => _colors[10];

  /// Text and icons on [tertiaryContainer].
  Color get onTertiaryContainer => _colors[11];

  /// The screen background (the scaffold).
  Color get background => _colors[12];

  /// Cards, sheets and list rows.
  Color get surface => _colors[13];

  /// Dialogs, menus and popovers.
  Color get surfaceElevated => _colors[14];

  /// Filled inputs, search bars and chips.
  Color get fill => _colors[15];

  /// Snackbars and tooltips: a surface in the opposite brightness.
  Color get inverseSurface => _colors[16];

  /// Text and icons on [inverseSurface].
  Color get onInverseSurface => _colors[17];

  /// Body text and primary icons.
  Color get text => _colors[18];

  /// Subtitles and secondary icons.
  Color get textSecondary => _colors[19];

  /// Hints, timestamps and placeholders. Use it for non-essential text only.
  Color get textTertiary => _colors[20];

  /// Disabled labels and icons.
  Color get textDisabled => _colors[21];

  /// Inline links.
  Color get link => _colors[22];

  /// Input borders, outlined buttons and checkboxes.
  Color get border => _colors[23];

  /// Dividers and hairlines.
  Color get divider => _colors[24];

  /// Focus rings.
  Color get focus => _colors[25];

  /// Errors.
  Color get error => _colors[26];

  /// Text and icons on [error].
  Color get onError => _colors[27];

  /// A soft background for error messages.
  Color get errorContainer => _colors[28];

  /// Text and icons on [errorContainer].
  Color get onErrorContainer => _colors[29];

  /// Success and confirmations.
  Color get success => _colors[30];

  /// Text and icons on [success].
  Color get onSuccess => _colors[31];

  /// A soft background for success messages.
  Color get successContainer => _colors[32];

  /// Text and icons on [successContainer].
  Color get onSuccessContainer => _colors[33];

  /// Warnings.
  Color get warning => _colors[34];

  /// Text and icons on [warning].
  Color get onWarning => _colors[35];

  /// A soft background for warnings.
  Color get warningContainer => _colors[36];

  /// Text and icons on [warningContainer].
  Color get onWarningContainer => _colors[37];

  /// Neutral information.
  Color get info => _colors[38];

  /// Text and icons on [info].
  Color get onInfo => _colors[39];

  /// A soft background for information messages.
  Color get infoContainer => _colors[40];

  /// Text and icons on [infoContainer].
  Color get onInfoContainer => _colors[41];

  /// The pressed and hover tint for custom widgets.
  Color get overlay => _colors[42];

  /// The text selection highlight.
  Color get selection => _colors[43];

  /// Loading placeholders.
  Color get skeleton => _colors[44];

  /// The moving highlight of a [skeleton] shimmer.
  Color get skeletonHighlight => _colors[45];

  /// Modal barriers behind dialogs and sheets.
  Color get scrim => _colors[46];

  /// Shadows.
  Color get shadow => _colors[47];

  /// The value of a custom [token] in this palette.
  ///
  /// In light palettes that's the token's own value. In dark palettes it's
  /// [ColorToken.dark], or a color derived from the light value and
  /// [ColorToken.role]. Values set with [withTokens] win over both.
  Color resolve(ColorToken token) {
    final explicit = _tokens[token.id];
    if (explicit != null) return explicit;
    final from = _lerpFrom;
    final to = _lerpTo;
    if (from != null && to != null) {
      return Color.lerp(from.resolve(token), to.resolve(token), _t)!;
    }
    if (brightness == Brightness.light) return token.light;
    return token.dark ??
        _derived.putIfAbsent(token, () => deriveCustomToken(token, this));
  }

  /// Returns a copy where the given custom tokens have the given values.
  ResolvedPalette withTokens(Map<ColorToken, Color> values) =>
      ResolvedPalette.fromList(
        brightness,
        _colors,
        style: style,
        tokens: {
          ..._tokens,
          for (final entry in values.entries) entry.key.id: entry.value,
        },
      );

  /// How well each foreground/background pair reads, against WCAG 2.2
  /// minimums.
  ///
  /// ```dart
  /// expect(palette.contrastReport().failures, isEmpty);
  /// ```
  ContrastReport contrastReport() => ContrastReport.of(this);

  @override
  ResolvedPalette copyWith({
    Brightness? brightness,
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? onSecondaryContainer,
    Color? tertiary,
    Color? onTertiary,
    Color? tertiaryContainer,
    Color? onTertiaryContainer,
    Color? background,
    Color? surface,
    Color? surfaceElevated,
    Color? fill,
    Color? inverseSurface,
    Color? onInverseSurface,
    Color? text,
    Color? textSecondary,
    Color? textTertiary,
    Color? textDisabled,
    Color? link,
    Color? border,
    Color? divider,
    Color? focus,
    Color? error,
    Color? onError,
    Color? errorContainer,
    Color? onErrorContainer,
    Color? success,
    Color? onSuccess,
    Color? successContainer,
    Color? onSuccessContainer,
    Color? warning,
    Color? onWarning,
    Color? warningContainer,
    Color? onWarningContainer,
    Color? info,
    Color? onInfo,
    Color? infoContainer,
    Color? onInfoContainer,
    Color? overlay,
    Color? selection,
    Color? skeleton,
    Color? skeletonHighlight,
    Color? scrim,
    Color? shadow,
    DarkStyle? style,
  }) => ResolvedPalette.fromList(
    brightness ?? this.brightness,
    [
      primary ?? this.primary,
      onPrimary ?? this.onPrimary,
      primaryContainer ?? this.primaryContainer,
      onPrimaryContainer ?? this.onPrimaryContainer,
      secondary ?? this.secondary,
      onSecondary ?? this.onSecondary,
      secondaryContainer ?? this.secondaryContainer,
      onSecondaryContainer ?? this.onSecondaryContainer,
      tertiary ?? this.tertiary,
      onTertiary ?? this.onTertiary,
      tertiaryContainer ?? this.tertiaryContainer,
      onTertiaryContainer ?? this.onTertiaryContainer,
      background ?? this.background,
      surface ?? this.surface,
      surfaceElevated ?? this.surfaceElevated,
      fill ?? this.fill,
      inverseSurface ?? this.inverseSurface,
      onInverseSurface ?? this.onInverseSurface,
      text ?? this.text,
      textSecondary ?? this.textSecondary,
      textTertiary ?? this.textTertiary,
      textDisabled ?? this.textDisabled,
      link ?? this.link,
      border ?? this.border,
      divider ?? this.divider,
      focus ?? this.focus,
      error ?? this.error,
      onError ?? this.onError,
      errorContainer ?? this.errorContainer,
      onErrorContainer ?? this.onErrorContainer,
      success ?? this.success,
      onSuccess ?? this.onSuccess,
      successContainer ?? this.successContainer,
      onSuccessContainer ?? this.onSuccessContainer,
      warning ?? this.warning,
      onWarning ?? this.onWarning,
      warningContainer ?? this.warningContainer,
      onWarningContainer ?? this.onWarningContainer,
      info ?? this.info,
      onInfo ?? this.onInfo,
      infoContainer ?? this.infoContainer,
      onInfoContainer ?? this.onInfoContainer,
      overlay ?? this.overlay,
      selection ?? this.selection,
      skeleton ?? this.skeleton,
      skeletonHighlight ?? this.skeletonHighlight,
      scrim ?? this.scrim,
      shadow ?? this.shadow,
    ],
    style: style ?? this.style,
    tokens: _tokens,
  );

  @override
  ResolvedPalette lerp(covariant ResolvedPalette? other, double t) {
    if (other == null || identical(this, other)) return this;
    // Short-circuiting the ends keeps interrupted animations from stacking.
    if (t <= 0) return this;
    if (t >= 1) return other;
    return ResolvedPalette._lerped(
      t < 0.5 ? brightness : other.brightness,
      [
        for (var i = 0; i < _count; i++)
          Color.lerp(_colors[i], other._colors[i], t)!,
      ],
      t < 0.5 ? style : other.style,
      this,
      other,
      t,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedPalette &&
          other.brightness == brightness &&
          other.style == style &&
          listEquals(other._colors, _colors) &&
          mapEquals(other._tokens, _tokens) &&
          identical(other._lerpFrom, _lerpFrom) &&
          identical(other._lerpTo, _lerpTo) &&
          other._t == _t;

  @override
  int get hashCode => Object.hash(
    brightness,
    style,
    Object.hashAll(_colors),
    Object.hashAllUnordered(
      _tokens.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    _t,
  );

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(EnumProperty<Brightness>('brightness', brightness));
    for (final token in PaletteToken.values) {
      properties.add(ColorProperty(token.name, this[token]));
    }
  }
}
