import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'palette_token.dart';

// GENERATED by tool/generate_palette.py from tool/palette_tokens.py.
// Edit those and rerun instead of changing the token lists by hand.

/// The colors you choose for one brightness. Every token is optional.
///
/// Set the ones you care about and themeflow derives the rest, then derives
/// the other brightness from this one. Most apps set [primary] and maybe a
/// few more:
///
/// ```dart
/// const ThemePalette(primary: Color(0xFF3D5AFE));
/// const ThemePalette(primary: brand, background: Color(0xFFF7F7F5));
/// const ThemePalette.seed(Color(0xFF3D5AFE));
/// ThemePalette.fromTheme(AppTheme.light);
/// ```
///
/// In a dark slot (`ThemeFlow(dark: ...)`), a palette works as overrides on
/// top of the derived dark colors, so it can be as small as one color.
@immutable
class ThemePalette with Diagnosticable {
  /// Creates a palette from explicit colors.
  const ThemePalette({
    this.neutral,
    this.primary,
    this.onPrimary,
    this.primaryContainer,
    this.onPrimaryContainer,
    this.secondary,
    this.onSecondary,
    this.secondaryContainer,
    this.onSecondaryContainer,
    this.tertiary,
    this.onTertiary,
    this.tertiaryContainer,
    this.onTertiaryContainer,
    this.background,
    this.surface,
    this.surfaceElevated,
    this.fill,
    this.inverseSurface,
    this.onInverseSurface,
    this.text,
    this.textSecondary,
    this.textTertiary,
    this.textDisabled,
    this.link,
    this.border,
    this.divider,
    this.focus,
    this.error,
    this.onError,
    this.errorContainer,
    this.onErrorContainer,
    this.success,
    this.onSuccess,
    this.successContainer,
    this.onSuccessContainer,
    this.warning,
    this.onWarning,
    this.warningContainer,
    this.onWarningContainer,
    this.info,
    this.onInfo,
    this.infoContainer,
    this.onInfoContainer,
    this.overlay,
    this.selection,
    this.skeleton,
    this.skeletonHighlight,
    this.scrim,
    this.shadow,
  }) : seed = null,
       seedVariant = DynamicSchemeVariant.fidelity;

  /// Creates a Material 3 tonal palette from one [seed] color.
  ///
  /// This uses Flutter's own `ColorScheme.fromSeed`. The default
  /// [DynamicSchemeVariant.fidelity] keeps [primary] close to the seed, so a
  /// brand color stays recognisable. Any color you pass overrides the
  /// generated one.
  const ThemePalette.seed(
    Color this.seed, {
    this.seedVariant = DynamicSchemeVariant.fidelity,
    this.neutral,
    this.primary,
    this.onPrimary,
    this.primaryContainer,
    this.onPrimaryContainer,
    this.secondary,
    this.onSecondary,
    this.secondaryContainer,
    this.onSecondaryContainer,
    this.tertiary,
    this.onTertiary,
    this.tertiaryContainer,
    this.onTertiaryContainer,
    this.background,
    this.surface,
    this.surfaceElevated,
    this.fill,
    this.inverseSurface,
    this.onInverseSurface,
    this.text,
    this.textSecondary,
    this.textTertiary,
    this.textDisabled,
    this.link,
    this.border,
    this.divider,
    this.focus,
    this.error,
    this.onError,
    this.errorContainer,
    this.onErrorContainer,
    this.success,
    this.onSuccess,
    this.successContainer,
    this.onSuccessContainer,
    this.warning,
    this.onWarning,
    this.warningContainer,
    this.onWarningContainer,
    this.info,
    this.onInfo,
    this.infoContainer,
    this.onInfoContainer,
    this.overlay,
    this.selection,
    this.skeleton,
    this.skeletonHighlight,
    this.scrim,
    this.shadow,
  });

  const ThemePalette._raw({
    required this.seed,
    required this.seedVariant,
    required this.neutral,
    required this.primary,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.tertiary,
    required this.onTertiary,
    required this.tertiaryContainer,
    required this.onTertiaryContainer,
    required this.background,
    required this.surface,
    required this.surfaceElevated,
    required this.fill,
    required this.inverseSurface,
    required this.onInverseSurface,
    required this.text,
    required this.textSecondary,
    required this.textTertiary,
    required this.textDisabled,
    required this.link,
    required this.border,
    required this.divider,
    required this.focus,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.success,
    required this.onSuccess,
    required this.successContainer,
    required this.onSuccessContainer,
    required this.warning,
    required this.onWarning,
    required this.warningContainer,
    required this.onWarningContainer,
    required this.info,
    required this.onInfo,
    required this.infoContainer,
    required this.onInfoContainer,
    required this.overlay,
    required this.selection,
    required this.skeleton,
    required this.skeletonHighlight,
    required this.scrim,
    required this.shadow,
  });

  /// Reads a palette from a [ColorScheme], for example one from the
  /// `dynamic_color` package.
  factory ThemePalette.fromColorScheme(ColorScheme scheme) => ThemePalette(
    primary: scheme.primary,
    onPrimary: scheme.onPrimary,
    primaryContainer: scheme.primaryContainer,
    onPrimaryContainer: scheme.onPrimaryContainer,
    secondary: scheme.secondary,
    onSecondary: scheme.onSecondary,
    secondaryContainer: scheme.secondaryContainer,
    onSecondaryContainer: scheme.onSecondaryContainer,
    tertiary: scheme.tertiary,
    onTertiary: scheme.onTertiary,
    tertiaryContainer: scheme.tertiaryContainer,
    onTertiaryContainer: scheme.onTertiaryContainer,
    error: scheme.error,
    onError: scheme.onError,
    errorContainer: scheme.errorContainer,
    onErrorContainer: scheme.onErrorContainer,
    background: scheme.surface,
    surface: scheme.surfaceContainerLow,
    surfaceElevated: scheme.surfaceContainerHigh,
    fill: scheme.surfaceContainerHighest,
    inverseSurface: scheme.inverseSurface,
    onInverseSurface: scheme.onInverseSurface,
    text: scheme.onSurface,
    textSecondary: scheme.onSurfaceVariant,
    border: scheme.outline,
    divider: scheme.outlineVariant,
    shadow: scheme.shadow,
  );

  /// Reads a palette from an existing [ThemeData].
  ///
  /// This is what `ThemeFlow(base: ...)` uses when you don't give a palette.
  /// The main rules:
  ///
  /// * [primary] and the other brand colors come from `colorScheme`.
  /// * [background] is `scaffoldBackgroundColor`.
  /// * [surface] is `cardTheme.color`, else the Material 3 card color.
  /// * [surfaceElevated] is `dialogTheme.backgroundColor`, else the Material 3
  ///   dialog color.
  /// * [fill] is `inputDecorationTheme.fillColor`.
  /// * [text] is `textTheme.bodyLarge.color`, else `colorScheme.onSurface`.
  /// * [textSecondary] is `colorScheme.onSurfaceVariant`.
  /// * [textTertiary] is the input hint color, when set.
  /// * [border] is the enabled input border color, else `colorScheme.outline`.
  /// * [divider] is `dividerTheme.color`, else the Material 3 divider color.
  factory ThemePalette.fromTheme(ThemeData theme) {
    final scheme = theme.colorScheme;
    final m3 = theme.useMaterial3;
    final input = theme.inputDecorationTheme;
    final enabled = input.enabledBorder?.borderSide;
    final inputBorder =
        enabled == null ||
            enabled.style == BorderStyle.none ||
            enabled.width == 0
        ? null
        : enabled.color;
    return ThemePalette(
      primary: scheme.primary,
      onPrimary: scheme.onPrimary,
      primaryContainer: scheme.primaryContainer,
      onPrimaryContainer: scheme.onPrimaryContainer,
      secondary: scheme.secondary,
      onSecondary: scheme.onSecondary,
      secondaryContainer: scheme.secondaryContainer,
      onSecondaryContainer: scheme.onSecondaryContainer,
      tertiary: scheme.tertiary,
      onTertiary: scheme.onTertiary,
      tertiaryContainer: scheme.tertiaryContainer,
      onTertiaryContainer: scheme.onTertiaryContainer,
      error: scheme.error,
      onError: scheme.onError,
      errorContainer: scheme.errorContainer,
      onErrorContainer: scheme.onErrorContainer,
      background: theme.scaffoldBackgroundColor,
      surface:
          theme.cardTheme.color ??
          (m3 ? scheme.surfaceContainerLow : theme.cardColor),
      surfaceElevated:
          theme.dialogTheme.backgroundColor ??
          (m3 ? scheme.surfaceContainerHigh : scheme.surface),
      fill: input.fillColor ?? (m3 ? scheme.surfaceContainerHighest : null),
      inverseSurface: scheme.inverseSurface,
      onInverseSurface: scheme.onInverseSurface,
      text: theme.textTheme.bodyLarge?.color ?? scheme.onSurface,
      textSecondary: scheme.onSurfaceVariant,
      textTertiary: input.hintStyle?.color,
      textDisabled: theme.disabledColor,
      border: inputBorder ?? scheme.outline,
      divider:
          theme.dividerTheme.color ??
          (m3 ? scheme.outlineVariant : theme.dividerColor),
      selection: theme.textSelectionTheme.selectionColor,
      shadow: scheme.shadow,
    );
  }

  /// The seed color of a [ThemePalette.seed] palette, else null.
  final Color? seed;

  /// How [seed] is turned into a scheme.
  final DynamicSchemeVariant seedVariant;

  /// The tint for derived greys. Defaults to [primary]'s hue.
  final Color? neutral;

  /// Main brand color: filled buttons, selection and active states.
  final Color? primary;

  /// Text and icons on [primary].
  final Color? onPrimary;

  /// A soft tint of [primary] for chips, badges and selected backgrounds.
  final Color? primaryContainer;

  /// Text and icons on [primaryContainer].
  final Color? onPrimaryContainer;

  /// A quieter companion to [primary].
  final Color? secondary;

  /// Text and icons on [secondary].
  final Color? onSecondary;

  /// A soft tint of [secondary].
  final Color? secondaryContainer;

  /// Text and icons on [secondaryContainer].
  final Color? onSecondaryContainer;

  /// A contrasting accent.
  final Color? tertiary;

  /// Text and icons on [tertiary].
  final Color? onTertiary;

  /// A soft tint of [tertiary].
  final Color? tertiaryContainer;

  /// Text and icons on [tertiaryContainer].
  final Color? onTertiaryContainer;

  /// The screen background (the scaffold).
  final Color? background;

  /// Cards, sheets and list rows.
  final Color? surface;

  /// Dialogs, menus and popovers.
  final Color? surfaceElevated;

  /// Filled inputs, search bars and chips.
  final Color? fill;

  /// Snackbars and tooltips: a surface in the opposite brightness.
  final Color? inverseSurface;

  /// Text and icons on [inverseSurface].
  final Color? onInverseSurface;

  /// Body text and primary icons.
  final Color? text;

  /// Subtitles and secondary icons.
  final Color? textSecondary;

  /// Hints, timestamps and placeholders. Use it for non-essential text only.
  final Color? textTertiary;

  /// Disabled labels and icons.
  final Color? textDisabled;

  /// Inline links.
  final Color? link;

  /// Input borders, outlined buttons and checkboxes.
  final Color? border;

  /// Dividers and hairlines.
  final Color? divider;

  /// Focus rings.
  final Color? focus;

  /// Errors.
  final Color? error;

  /// Text and icons on [error].
  final Color? onError;

  /// A soft background for error messages.
  final Color? errorContainer;

  /// Text and icons on [errorContainer].
  final Color? onErrorContainer;

  /// Success and confirmations.
  final Color? success;

  /// Text and icons on [success].
  final Color? onSuccess;

  /// A soft background for success messages.
  final Color? successContainer;

  /// Text and icons on [successContainer].
  final Color? onSuccessContainer;

  /// Warnings.
  final Color? warning;

  /// Text and icons on [warning].
  final Color? onWarning;

  /// A soft background for warnings.
  final Color? warningContainer;

  /// Text and icons on [warningContainer].
  final Color? onWarningContainer;

  /// Neutral information.
  final Color? info;

  /// Text and icons on [info].
  final Color? onInfo;

  /// A soft background for information messages.
  final Color? infoContainer;

  /// Text and icons on [infoContainer].
  final Color? onInfoContainer;

  /// The pressed and hover tint for custom widgets.
  final Color? overlay;

  /// The text selection highlight.
  final Color? selection;

  /// Loading placeholders.
  final Color? skeleton;

  /// The moving highlight of a [skeleton] shimmer.
  final Color? skeletonHighlight;

  /// Modal barriers behind dialogs and sheets.
  final Color? scrim;

  /// Shadows.
  final Color? shadow;

  /// The color you set for [token], or null.
  Color? operator [](PaletteToken token) => values[token.index];

  /// Your colors, in [PaletteToken.values] order, with null where unset.
  List<Color?> get values => [
    primary,
    onPrimary,
    primaryContainer,
    onPrimaryContainer,
    secondary,
    onSecondary,
    secondaryContainer,
    onSecondaryContainer,
    tertiary,
    onTertiary,
    tertiaryContainer,
    onTertiaryContainer,
    background,
    surface,
    surfaceElevated,
    fill,
    inverseSurface,
    onInverseSurface,
    text,
    textSecondary,
    textTertiary,
    textDisabled,
    link,
    border,
    divider,
    focus,
    error,
    onError,
    errorContainer,
    onErrorContainer,
    success,
    onSuccess,
    successContainer,
    onSuccessContainer,
    warning,
    onWarning,
    warningContainer,
    onWarningContainer,
    info,
    onInfo,
    infoContainer,
    onInfoContainer,
    overlay,
    selection,
    skeleton,
    skeletonHighlight,
    scrim,
    shadow,
  ];

  /// Returns a copy with the given colors replaced.
  ThemePalette copyWith({
    Color? seed,
    DynamicSchemeVariant? seedVariant,
    Color? neutral,
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? onSecondaryContainer,
    Color? tertiary,
    Color? onTertiary,
    Color? tertiaryContainer,
    Color? onTertiaryContainer,
    Color? background,
    Color? surface,
    Color? surfaceElevated,
    Color? fill,
    Color? inverseSurface,
    Color? onInverseSurface,
    Color? text,
    Color? textSecondary,
    Color? textTertiary,
    Color? textDisabled,
    Color? link,
    Color? border,
    Color? divider,
    Color? focus,
    Color? error,
    Color? onError,
    Color? errorContainer,
    Color? onErrorContainer,
    Color? success,
    Color? onSuccess,
    Color? successContainer,
    Color? onSuccessContainer,
    Color? warning,
    Color? onWarning,
    Color? warningContainer,
    Color? onWarningContainer,
    Color? info,
    Color? onInfo,
    Color? infoContainer,
    Color? onInfoContainer,
    Color? overlay,
    Color? selection,
    Color? skeleton,
    Color? skeletonHighlight,
    Color? scrim,
    Color? shadow,
  }) => ThemePalette._raw(
    seed: seed ?? this.seed,
    seedVariant: seedVariant ?? this.seedVariant,
    neutral: neutral ?? this.neutral,
    primary: primary ?? this.primary,
    onPrimary: onPrimary ?? this.onPrimary,
    primaryContainer: primaryContainer ?? this.primaryContainer,
    onPrimaryContainer: onPrimaryContainer ?? this.onPrimaryContainer,
    secondary: secondary ?? this.secondary,
    onSecondary: onSecondary ?? this.onSecondary,
    secondaryContainer: secondaryContainer ?? this.secondaryContainer,
    onSecondaryContainer: onSecondaryContainer ?? this.onSecondaryContainer,
    tertiary: tertiary ?? this.tertiary,
    onTertiary: onTertiary ?? this.onTertiary,
    tertiaryContainer: tertiaryContainer ?? this.tertiaryContainer,
    onTertiaryContainer: onTertiaryContainer ?? this.onTertiaryContainer,
    background: background ?? this.background,
    surface: surface ?? this.surface,
    surfaceElevated: surfaceElevated ?? this.surfaceElevated,
    fill: fill ?? this.fill,
    inverseSurface: inverseSurface ?? this.inverseSurface,
    onInverseSurface: onInverseSurface ?? this.onInverseSurface,
    text: text ?? this.text,
    textSecondary: textSecondary ?? this.textSecondary,
    textTertiary: textTertiary ?? this.textTertiary,
    textDisabled: textDisabled ?? this.textDisabled,
    link: link ?? this.link,
    border: border ?? this.border,
    divider: divider ?? this.divider,
    focus: focus ?? this.focus,
    error: error ?? this.error,
    onError: onError ?? this.onError,
    errorContainer: errorContainer ?? this.errorContainer,
    onErrorContainer: onErrorContainer ?? this.onErrorContainer,
    success: success ?? this.success,
    onSuccess: onSuccess ?? this.onSuccess,
    successContainer: successContainer ?? this.successContainer,
    onSuccessContainer: onSuccessContainer ?? this.onSuccessContainer,
    warning: warning ?? this.warning,
    onWarning: onWarning ?? this.onWarning,
    warningContainer: warningContainer ?? this.warningContainer,
    onWarningContainer: onWarningContainer ?? this.onWarningContainer,
    info: info ?? this.info,
    onInfo: onInfo ?? this.onInfo,
    infoContainer: infoContainer ?? this.infoContainer,
    onInfoContainer: onInfoContainer ?? this.onInfoContainer,
    overlay: overlay ?? this.overlay,
    selection: selection ?? this.selection,
    skeleton: skeleton ?? this.skeleton,
    skeletonHighlight: skeletonHighlight ?? this.skeletonHighlight,
    scrim: scrim ?? this.scrim,
    shadow: shadow ?? this.shadow,
  );

  /// Returns this palette with every color set in [other] on top.
  ///
  /// When [other] is a seed palette, its seed replaces this one's.
  ThemePalette merge(ThemePalette? other) {
    if (other == null) return this;
    return ThemePalette._raw(
      seed: other.seed ?? seed,
      seedVariant: other.seed != null ? other.seedVariant : seedVariant,
      neutral: other.neutral ?? neutral,
      primary: other.primary ?? primary,
      onPrimary: other.onPrimary ?? onPrimary,
      primaryContainer: other.primaryContainer ?? primaryContainer,
      onPrimaryContainer: other.onPrimaryContainer ?? onPrimaryContainer,
      secondary: other.secondary ?? secondary,
      onSecondary: other.onSecondary ?? onSecondary,
      secondaryContainer: other.secondaryContainer ?? secondaryContainer,
      onSecondaryContainer: other.onSecondaryContainer ?? onSecondaryContainer,
      tertiary: other.tertiary ?? tertiary,
      onTertiary: other.onTertiary ?? onTertiary,
      tertiaryContainer: other.tertiaryContainer ?? tertiaryContainer,
      onTertiaryContainer: other.onTertiaryContainer ?? onTertiaryContainer,
      background: other.background ?? background,
      surface: other.surface ?? surface,
      surfaceElevated: other.surfaceElevated ?? surfaceElevated,
      fill: other.fill ?? fill,
      inverseSurface: other.inverseSurface ?? inverseSurface,
      onInverseSurface: other.onInverseSurface ?? onInverseSurface,
      text: other.text ?? text,
      textSecondary: other.textSecondary ?? textSecondary,
      textTertiary: other.textTertiary ?? textTertiary,
      textDisabled: other.textDisabled ?? textDisabled,
      link: other.link ?? link,
      border: other.border ?? border,
      divider: other.divider ?? divider,
      focus: other.focus ?? focus,
      error: other.error ?? error,
      onError: other.onError ?? onError,
      errorContainer: other.errorContainer ?? errorContainer,
      onErrorContainer: other.onErrorContainer ?? onErrorContainer,
      success: other.success ?? success,
      onSuccess: other.onSuccess ?? onSuccess,
      successContainer: other.successContainer ?? successContainer,
      onSuccessContainer: other.onSuccessContainer ?? onSuccessContainer,
      warning: other.warning ?? warning,
      onWarning: other.onWarning ?? onWarning,
      warningContainer: other.warningContainer ?? warningContainer,
      onWarningContainer: other.onWarningContainer ?? onWarningContainer,
      info: other.info ?? info,
      onInfo: other.onInfo ?? onInfo,
      infoContainer: other.infoContainer ?? infoContainer,
      onInfoContainer: other.onInfoContainer ?? onInfoContainer,
      overlay: other.overlay ?? overlay,
      selection: other.selection ?? selection,
      skeleton: other.skeleton ?? skeleton,
      skeletonHighlight: other.skeletonHighlight ?? skeletonHighlight,
      scrim: other.scrim ?? scrim,
      shadow: other.shadow ?? shadow,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is ThemePalette &&
      other.seed == seed &&
      other.seedVariant == seedVariant &&
      other.neutral == neutral &&
      listEquals(other.values, values);

  @override
  int get hashCode =>
      Object.hash(seed, seedVariant, neutral, Object.hashAll(values));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties
      ..add(ColorProperty('seed', seed, defaultValue: null))
      ..add(EnumProperty<DynamicSchemeVariant>('seedVariant', seedVariant))
      ..add(ColorProperty('neutral', neutral, defaultValue: null))
      ..add(ColorProperty('primary', primary, defaultValue: null))
      ..add(ColorProperty('onPrimary', onPrimary, defaultValue: null))
      ..add(
        ColorProperty('primaryContainer', primaryContainer, defaultValue: null),
      )
      ..add(
        ColorProperty(
          'onPrimaryContainer',
          onPrimaryContainer,
          defaultValue: null,
        ),
      )
      ..add(ColorProperty('secondary', secondary, defaultValue: null))
      ..add(ColorProperty('onSecondary', onSecondary, defaultValue: null))
      ..add(
        ColorProperty(
          'secondaryContainer',
          secondaryContainer,
          defaultValue: null,
        ),
      )
      ..add(
        ColorProperty(
          'onSecondaryContainer',
          onSecondaryContainer,
          defaultValue: null,
        ),
      )
      ..add(ColorProperty('tertiary', tertiary, defaultValue: null))
      ..add(ColorProperty('onTertiary', onTertiary, defaultValue: null))
      ..add(
        ColorProperty(
          'tertiaryContainer',
          tertiaryContainer,
          defaultValue: null,
        ),
      )
      ..add(
        ColorProperty(
          'onTertiaryContainer',
          onTertiaryContainer,
          defaultValue: null,
        ),
      )
      ..add(ColorProperty('background', background, defaultValue: null))
      ..add(ColorProperty('surface', surface, defaultValue: null))
      ..add(
        ColorProperty('surfaceElevated', surfaceElevated, defaultValue: null),
      )
      ..add(ColorProperty('fill', fill, defaultValue: null))
      ..add(ColorProperty('inverseSurface', inverseSurface, defaultValue: null))
      ..add(
        ColorProperty('onInverseSurface', onInverseSurface, defaultValue: null),
      )
      ..add(ColorProperty('text', text, defaultValue: null))
      ..add(ColorProperty('textSecondary', textSecondary, defaultValue: null))
      ..add(ColorProperty('textTertiary', textTertiary, defaultValue: null))
      ..add(ColorProperty('textDisabled', textDisabled, defaultValue: null))
      ..add(ColorProperty('link', link, defaultValue: null))
      ..add(ColorProperty('border', border, defaultValue: null))
      ..add(ColorProperty('divider', divider, defaultValue: null))
      ..add(ColorProperty('focus', focus, defaultValue: null))
      ..add(ColorProperty('error', error, defaultValue: null))
      ..add(ColorProperty('onError', onError, defaultValue: null))
      ..add(ColorProperty('errorContainer', errorContainer, defaultValue: null))
      ..add(
        ColorProperty('onErrorContainer', onErrorContainer, defaultValue: null),
      )
      ..add(ColorProperty('success', success, defaultValue: null))
      ..add(ColorProperty('onSuccess', onSuccess, defaultValue: null))
      ..add(
        ColorProperty('successContainer', successContainer, defaultValue: null),
      )
      ..add(
        ColorProperty(
          'onSuccessContainer',
          onSuccessContainer,
          defaultValue: null,
        ),
      )
      ..add(ColorProperty('warning', warning, defaultValue: null))
      ..add(ColorProperty('onWarning', onWarning, defaultValue: null))
      ..add(
        ColorProperty('warningContainer', warningContainer, defaultValue: null),
      )
      ..add(
        ColorProperty(
          'onWarningContainer',
          onWarningContainer,
          defaultValue: null,
        ),
      )
      ..add(ColorProperty('info', info, defaultValue: null))
      ..add(ColorProperty('onInfo', onInfo, defaultValue: null))
      ..add(ColorProperty('infoContainer', infoContainer, defaultValue: null))
      ..add(
        ColorProperty('onInfoContainer', onInfoContainer, defaultValue: null),
      )
      ..add(ColorProperty('overlay', overlay, defaultValue: null))
      ..add(ColorProperty('selection', selection, defaultValue: null))
      ..add(ColorProperty('skeleton', skeleton, defaultValue: null))
      ..add(
        ColorProperty(
          'skeletonHighlight',
          skeletonHighlight,
          defaultValue: null,
        ),
      )
      ..add(ColorProperty('scrim', scrim, defaultValue: null))
      ..add(ColorProperty('shadow', shadow, defaultValue: null));
  }
}
