#!/usr/bin/env python3
"""Generates the token lists in lib/src/palette/ from tool/palette_tokens.py.

palette_token.dart, theme_palette.dart and resolved_palette.dart all list the
48 tokens. They're generated from one spec so they can't drift apart. To add
or change a token, edit palette_tokens.py and run:

    python3 tool/generate_palette.py && dart format lib
"""
import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from palette_tokens import T  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'lib', 'src', 'palette') + os.sep
HDR='// GENERATED by tool/generate_palette.py from tool/palette_tokens.py.\n// Edit those and rerun instead of changing the token lists by hand.\n'

def doc(text, indent='  '):
    lines = textwrap.wrap(text, 76 - len(indent))
    return ''.join(f'{indent}/// {l}\n' for l in lines)

# ---------------- palette_token.dart
s = "import 'color_token.dart';\n\n"
s += HDR + '\n'
s += "/// The 48 tokens of a themeflow palette.\n///\n/// Read them with `context.palette.surface` and the like. Use this enum to\n/// loop over tokens, or to look one up with `palette[PaletteToken.surface]`.\nenum PaletteToken {\n"
for i,(n,role,group,d) in enumerate(T):
    s += doc(d)
    s += f"  {n}(TokenRole.{role}, '{group}'){',' if i < len(T)-1 else ';'}\n"
    if i < len(T)-1: s += '\n'
s += "\n  const PaletteToken(this.role, this.group);\n\n  /// What the token is for.\n  final TokenRole role;\n\n  /// The token's group: Brand, Surfaces, Content, Lines, Status or Effects.\n  final String group;\n}\n"
open(OUT+'palette_token.dart','w').write(s)

# ---------------- theme_palette.dart
fields = ''.join(doc(d) + f'  final Color? {n};\n\n' for n,_,_,d in T)
ctor_params = ''.join(f'    this.{n},\n' for n,_,_,_ in T)
raw_params = ''.join(f'    required this.{n},\n' for n,_,_,_ in T)
copy_params = ''.join(f'    Color? {n},\n' for n,_,_,_ in T)
copy_args = ''.join(f'    {n}: {n} ?? this.{n},\n' for n,_,_,_ in T)
merge_args = ''.join(f'      {n}: other.{n} ?? {n},\n' for n,_,_,_ in T)
values = ''.join(f'    {n},\n' for n,_,_,_ in T)
props = ''.join(f"      ..add(ColorProperty('{n}', {n}, defaultValue: null))\n" for n,_,_,_ in T)
s = f"""import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'palette_token.dart';

{HDR}
/// The colors you choose for one brightness. Every token is optional.
///
/// Set the ones you care about and themeflow derives the rest, then derives
/// the other brightness from this one. Most apps set [primary] and maybe a
/// few more:
///
/// ```dart
/// const ThemePalette(primary: Color(0xFF3D5AFE));
/// const ThemePalette(primary: brand, background: Color(0xFFF7F7F5));
/// const ThemePalette.seed(Color(0xFF3D5AFE));
/// ThemePalette.fromTheme(AppTheme.light);
/// ```
///
/// In a dark slot (`ThemeFlow(dark: ...)`), a palette works as overrides on
/// top of the derived dark colors, so it can be as small as one color.
@immutable
class ThemePalette with Diagnosticable {{
  /// Creates a palette from explicit colors.
  const ThemePalette({{
    this.neutral,
{ctor_params}  }}) : seed = null,
       seedVariant = DynamicSchemeVariant.fidelity;

  /// Creates a Material 3 tonal palette from one [seed] color.
  ///
  /// This uses Flutter's own `ColorScheme.fromSeed`. The default
  /// [DynamicSchemeVariant.fidelity] keeps [primary] close to the seed, so a
  /// brand color stays recognisable. Any color you pass overrides the
  /// generated one.
  const ThemePalette.seed(
    Color this.seed, {{
    this.seedVariant = DynamicSchemeVariant.fidelity,
    this.neutral,
{ctor_params}  }});

  const ThemePalette._raw({{
    required this.seed,
    required this.seedVariant,
    required this.neutral,
{raw_params}  }});

  /// Reads a palette from a [ColorScheme], for example one from the
  /// `dynamic_color` package.
  factory ThemePalette.fromColorScheme(ColorScheme scheme) => ThemePalette(
    primary: scheme.primary,
    onPrimary: scheme.onPrimary,
    primaryContainer: scheme.primaryContainer,
    onPrimaryContainer: scheme.onPrimaryContainer,
    secondary: scheme.secondary,
    onSecondary: scheme.onSecondary,
    secondaryContainer: scheme.secondaryContainer,
    onSecondaryContainer: scheme.onSecondaryContainer,
    tertiary: scheme.tertiary,
    onTertiary: scheme.onTertiary,
    tertiaryContainer: scheme.tertiaryContainer,
    onTertiaryContainer: scheme.onTertiaryContainer,
    error: scheme.error,
    onError: scheme.onError,
    errorContainer: scheme.errorContainer,
    onErrorContainer: scheme.onErrorContainer,
    background: scheme.surface,
    surface: scheme.surfaceContainerLow,
    surfaceElevated: scheme.surfaceContainerHigh,
    fill: scheme.surfaceContainerHighest,
    inverseSurface: scheme.inverseSurface,
    onInverseSurface: scheme.onInverseSurface,
    text: scheme.onSurface,
    textSecondary: scheme.onSurfaceVariant,
    border: scheme.outline,
    divider: scheme.outlineVariant,
    shadow: scheme.shadow,
  );

  /// Reads a palette from an existing [ThemeData].
  ///
  /// This is what `ThemeFlow(base: ...)` uses when you don't give a palette.
  /// The main rules:
  ///
  /// * [primary] and the other brand colors come from `colorScheme`.
  /// * [background] is `scaffoldBackgroundColor`.
  /// * [surface] is `cardTheme.color`, else the Material 3 card color.
  /// * [surfaceElevated] is `dialogTheme.backgroundColor`, else the Material 3
  ///   dialog color.
  /// * [fill] is `inputDecorationTheme.fillColor`.
  /// * [text] is `textTheme.bodyLarge.color`, else `colorScheme.onSurface`.
  /// * [textSecondary] is `colorScheme.onSurfaceVariant`.
  /// * [textTertiary] is the input hint color, when set.
  /// * [border] is the enabled input border color, else `colorScheme.outline`.
  /// * [divider] is `dividerTheme.color`, else the Material 3 divider color.
  factory ThemePalette.fromTheme(ThemeData theme) {{
    final scheme = theme.colorScheme;
    final m3 = theme.useMaterial3;
    final input = theme.inputDecorationTheme;
    final enabled = input.enabledBorder?.borderSide;
    final inputBorder =
        enabled == null || enabled.style == BorderStyle.none || enabled.width == 0
        ? null
        : enabled.color;
    return ThemePalette(
      primary: scheme.primary,
      onPrimary: scheme.onPrimary,
      primaryContainer: scheme.primaryContainer,
      onPrimaryContainer: scheme.onPrimaryContainer,
      secondary: scheme.secondary,
      onSecondary: scheme.onSecondary,
      secondaryContainer: scheme.secondaryContainer,
      onSecondaryContainer: scheme.onSecondaryContainer,
      tertiary: scheme.tertiary,
      onTertiary: scheme.onTertiary,
      tertiaryContainer: scheme.tertiaryContainer,
      onTertiaryContainer: scheme.onTertiaryContainer,
      error: scheme.error,
      onError: scheme.onError,
      errorContainer: scheme.errorContainer,
      onErrorContainer: scheme.onErrorContainer,
      background: theme.scaffoldBackgroundColor,
      surface: theme.cardTheme.color ?? (m3 ? scheme.surfaceContainerLow : theme.cardColor),
      surfaceElevated:
          theme.dialogTheme.backgroundColor ?? (m3 ? scheme.surfaceContainerHigh : scheme.surface),
      fill: input.fillColor ?? (m3 ? scheme.surfaceContainerHighest : null),
      inverseSurface: scheme.inverseSurface,
      onInverseSurface: scheme.onInverseSurface,
      text: theme.textTheme.bodyLarge?.color ?? scheme.onSurface,
      textSecondary: scheme.onSurfaceVariant,
      textTertiary: input.hintStyle?.color,
      textDisabled: theme.disabledColor,
      border: inputBorder ?? scheme.outline,
      divider: theme.dividerTheme.color ?? (m3 ? scheme.outlineVariant : theme.dividerColor),
      selection: theme.textSelectionTheme.selectionColor,
      shadow: scheme.shadow,
    );
  }}

  /// The seed color of a [ThemePalette.seed] palette, else null.
  final Color? seed;

  /// How [seed] is turned into a scheme.
  final DynamicSchemeVariant seedVariant;

  /// The tint for derived greys. Defaults to [primary]'s hue.
  final Color? neutral;

{fields}  /// The color you set for [token], or null.
  Color? operator [](PaletteToken token) => values[token.index];

  /// Your colors, in [PaletteToken.values] order, with null where unset.
  List<Color?> get values => [
{values}  ];

  /// Returns a copy with the given colors replaced.
  ThemePalette copyWith({{
    Color? seed,
    DynamicSchemeVariant? seedVariant,
    Color? neutral,
{copy_params}  }}) => ThemePalette._raw(
    seed: seed ?? this.seed,
    seedVariant: seedVariant ?? this.seedVariant,
    neutral: neutral ?? this.neutral,
{copy_args}  );

  /// Returns this palette with every color set in [other] on top.
  ///
  /// When [other] is a seed palette, its seed replaces this one's.
  ThemePalette merge(ThemePalette? other) {{
    if (other == null) return this;
    return ThemePalette._raw(
      seed: other.seed ?? seed,
      seedVariant: other.seed != null ? other.seedVariant : seedVariant,
      neutral: other.neutral ?? neutral,
{merge_args}    );
  }}

  @override
  bool operator ==(Object other) =>
      other is ThemePalette &&
      other.seed == seed &&
      other.seedVariant == seedVariant &&
      other.neutral == neutral &&
      listEquals(other.values, values);

  @override
  int get hashCode => Object.hash(seed, seedVariant, neutral, Object.hashAll(values));

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {{
    super.debugFillProperties(properties);
    properties
      ..add(ColorProperty('seed', seed, defaultValue: null))
      ..add(EnumProperty<DynamicSchemeVariant>('seedVariant', seedVariant))
      ..add(ColorProperty('neutral', neutral, defaultValue: null))
{props.rstrip()};
  }}
}}
"""
open(OUT+'theme_palette.dart','w').write(s)

# ---------------- resolved_palette.dart
getters = ''.join(doc(d) + f'  Color get {n} => _colors[{i}];\n\n' for i,(n,_,_,d) in enumerate(T))
fparams = ''.join(f'    required Color {n},\n' for n,_,_,_ in T)
flist = ''.join(f'    {n},\n' for n,_,_,_ in T)
cparams = ''.join(f'    Color? {n},\n' for n,_,_,_ in T)
clist = ''.join(f'      {n} ?? this.{n},\n' for n,_,_,_ in T)
s = f"""import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'color_token.dart';
import 'contrast_report.dart';
import 'dark_style.dart';
import 'derive.dart' show deriveCustomToken;
import 'palette_scope.dart';
import 'palette_token.dart';

{HDR}
/// Every token of a palette with a concrete value, for one brightness.
///
/// themeflow puts this in your `ThemeData` as a [ThemeExtension]. That way it
/// switches with the theme, animates with it, and reaches dialogs and sheets.
/// Read it with `context.palette` or [ResolvedPalette.of].
@immutable
class ResolvedPalette extends ThemeExtension<ResolvedPalette>
    with Diagnosticable {{
  /// Creates a palette with every token set explicitly.
  ///
  /// Most apps never call this. `ThemeFlow` and [resolvePalettes] build
  /// palettes from a `ThemePalette`.
  factory ResolvedPalette({{
    required Brightness brightness,
{fparams}    DarkStyle style = const DarkStyle(),
  }}) => ResolvedPalette.fromList(brightness, [
{flist}  ], style: style);

  /// Creates a palette from [colors], in [PaletteToken.values] order.
  ResolvedPalette.fromList(
    this.brightness,
    List<Color> colors, {{
    this.style = const DarkStyle(),
    Map<String, Color> tokens = const {{}},
  }}) : assert(colors.length == _count, 'Expected $_count colors.'),
       _colors = List<Color>.unmodifiable(colors),
       _tokens = Map<String, Color>.unmodifiable(tokens),
       _lerpFrom = null,
       _lerpTo = null,
       _t = 0;

  ResolvedPalette._lerped(
    this.brightness,
    List<Color> colors,
    this.style,
    ResolvedPalette from,
    ResolvedPalette to,
    double t,
  ) : _colors = List<Color>.unmodifiable(colors),
      _tokens = const {{}},
      _lerpFrom = from,
      _lerpTo = to,
      _t = t;

  static final int _count = PaletteToken.values.length;

  /// Light or dark.
  final Brightness brightness;

  /// The style dark colors were derived with. Custom tokens use it too.
  final DarkStyle style;

  final List<Color> _colors;
  final Map<String, Color> _tokens;
  final ResolvedPalette? _lerpFrom;
  final ResolvedPalette? _lerpTo;
  final double _t;

  // Memo of derived custom tokens. It only ever caches a pure function of
  // this palette, so the palette stays immutable in every observable way.
  final Map<ColorToken, Color> _derived = <ColorToken, Color>{{}};

  /// The nearest palette: from the current `Theme`, else from `ThemeFlow`.
  ///
  /// Widgets that call this rebuild when the theme changes.
  static ResolvedPalette of(BuildContext context) {{
    final palette = maybeOf(context);
    if (palette != null) return palette;
    throw FlutterError.fromParts(<DiagnosticsNode>[
      ErrorSummary('No themeflow palette found in this context.'),
      ErrorHint(
        'Pass t.light and t.dark from ThemeFlow\\'s builder to your '
        'MaterialApp (theme: t.light, darkTheme: t.dark), or put the app '
        'inside a ThemeFlow widget.',
      ),
    ]);
  }}

  /// Like [of], but returns null when there's no palette.
  static ResolvedPalette? maybeOf(BuildContext context) =>
      Theme.of(context).extension<ResolvedPalette>() ??
      PaletteScope.maybeOf(context);

  /// The value of [token].
  Color operator [](PaletteToken token) => _colors[token.index];

  /// Every token's value, in [PaletteToken.values] order.
  List<Color> get colors => _colors;

{getters}  /// The value of a custom [token] in this palette.
  ///
  /// In light palettes that's the token's own value. In dark palettes it's
  /// [ColorToken.dark], or a color derived from the light value and
  /// [ColorToken.role]. Values set with [withTokens] win over both.
  Color resolve(ColorToken token) {{
    final explicit = _tokens[token.id];
    if (explicit != null) return explicit;
    final from = _lerpFrom;
    final to = _lerpTo;
    if (from != null && to != null) {{
      return Color.lerp(from.resolve(token), to.resolve(token), _t)!;
    }}
    if (brightness == Brightness.light) return token.light;
    return token.dark ??
        _derived.putIfAbsent(token, () => deriveCustomToken(token, this));
  }}

  /// Returns a copy where the given custom tokens have the given values.
  ResolvedPalette withTokens(Map<ColorToken, Color> values) =>
      ResolvedPalette.fromList(
        brightness,
        _colors,
        style: style,
        tokens: {{
          ..._tokens,
          for (final entry in values.entries) entry.key.id: entry.value,
        }},
      );

  /// How well each foreground/background pair reads, against WCAG 2.2
  /// minimums.
  ///
  /// ```dart
  /// expect(palette.contrastReport().failures, isEmpty);
  /// ```
  ContrastReport contrastReport() => ContrastReport.of(this);

  @override
  ResolvedPalette copyWith({{
    Brightness? brightness,
{cparams}    DarkStyle? style,
  }}) => ResolvedPalette.fromList(
    brightness ?? this.brightness,
    [
{clist}    ],
    style: style ?? this.style,
    tokens: _tokens,
  );

  @override
  ResolvedPalette lerp(covariant ResolvedPalette? other, double t) {{
    if (other == null || identical(this, other)) return this;
    // Short-circuiting the ends keeps interrupted animations from stacking.
    if (t <= 0) return this;
    if (t >= 1) return other;
    return ResolvedPalette._lerped(
      t < 0.5 ? brightness : other.brightness,
      [
        for (var i = 0; i < _count; i++)
          Color.lerp(_colors[i], other._colors[i], t)!,
      ],
      t < 0.5 ? style : other.style,
      this,
      other,
      t,
    );
  }}

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedPalette &&
          other.brightness == brightness &&
          other.style == style &&
          listEquals(other._colors, _colors) &&
          mapEquals(other._tokens, _tokens) &&
          identical(other._lerpFrom, _lerpFrom) &&
          identical(other._lerpTo, _lerpTo) &&
          other._t == _t;

  @override
  int get hashCode => Object.hash(
    brightness,
    style,
    Object.hashAll(_colors),
    Object.hashAllUnordered(_tokens.entries.map((e) => Object.hash(e.key, e.value))),
    _t,
  );

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {{
    super.debugFillProperties(properties);
    properties.add(EnumProperty<Brightness>('brightness', brightness));
    for (final token in PaletteToken.values) {{
      properties.add(ColorProperty(token.name, this[token]));
    }}
  }}
}}
"""
open(OUT+'resolved_palette.dart','w').write(s)
print('generated palette_token.dart, theme_palette.dart, resolved_palette.dart')
