# The 48 palette tokens: name, role, group, dartdoc. Used by generate_palette.py.
# name, role, group, doc
T = [
 ('primary','accent','Brand','Main brand color: filled buttons, selection and active states.'),
 ('onPrimary','onColor','Brand','Text and icons on [primary].'),
 ('primaryContainer','container','Brand','A soft tint of [primary] for chips, badges and selected backgrounds.'),
 ('onPrimaryContainer','onColor','Brand','Text and icons on [primaryContainer].'),
 ('secondary','accent','Brand','A quieter companion to [primary].'),
 ('onSecondary','onColor','Brand','Text and icons on [secondary].'),
 ('secondaryContainer','container','Brand','A soft tint of [secondary].'),
 ('onSecondaryContainer','onColor','Brand','Text and icons on [secondaryContainer].'),
 ('tertiary','accent','Brand','A contrasting accent.'),
 ('onTertiary','onColor','Brand','Text and icons on [tertiary].'),
 ('tertiaryContainer','container','Brand','A soft tint of [tertiary].'),
 ('onTertiaryContainer','onColor','Brand','Text and icons on [tertiaryContainer].'),
 ('background','surface','Surfaces','The screen background (the scaffold).'),
 ('surface','surface','Surfaces','Cards, sheets and list rows.'),
 ('surfaceElevated','surface','Surfaces','Dialogs, menus and popovers.'),
 ('fill','surface','Surfaces','Filled inputs, search bars and chips.'),
 ('inverseSurface','surface','Surfaces','Snackbars and tooltips: a surface in the opposite brightness.'),
 ('onInverseSurface','onColor','Surfaces','Text and icons on [inverseSurface].'),
 ('text','content','Content','Body text and primary icons.'),
 ('textSecondary','content','Content','Subtitles and secondary icons.'),
 ('textTertiary','content','Content','Hints, timestamps and placeholders. Use it for non-essential text only.'),
 ('textDisabled','content','Content','Disabled labels and icons.'),
 ('link','accent','Content','Inline links.'),
 ('border','outline','Lines','Input borders, outlined buttons and checkboxes.'),
 ('divider','outline','Lines','Dividers and hairlines.'),
 ('focus','accent','Lines','Focus rings.'),
 ('error','accent','Status','Errors.'),
 ('onError','onColor','Status','Text and icons on [error].'),
 ('errorContainer','container','Status','A soft background for error messages.'),
 ('onErrorContainer','onColor','Status','Text and icons on [errorContainer].'),
 ('success','accent','Status','Success and confirmations.'),
 ('onSuccess','onColor','Status','Text and icons on [success].'),
 ('successContainer','container','Status','A soft background for success messages.'),
 ('onSuccessContainer','onColor','Status','Text and icons on [successContainer].'),
 ('warning','accent','Status','Warnings.'),
 ('onWarning','onColor','Status','Text and icons on [warning].'),
 ('warningContainer','container','Status','A soft background for warnings.'),
 ('onWarningContainer','onColor','Status','Text and icons on [warningContainer].'),
 ('info','accent','Status','Neutral information.'),
 ('onInfo','onColor','Status','Text and icons on [info].'),
 ('infoContainer','container','Status','A soft background for information messages.'),
 ('onInfoContainer','onColor','Status','Text and icons on [infoContainer].'),
 ('overlay','content','Effects','The pressed and hover tint for custom widgets.'),
 ('selection','accent','Effects','The text selection highlight.'),
 ('skeleton','surface','Effects','Loading placeholders.'),
 ('skeletonHighlight','surface','Effects','The moving highlight of a [skeleton] shimmer.'),
 ('scrim','fixed','Effects','Modal barriers behind dialogs and sheets.'),
 ('shadow','fixed','Effects','Shadows.'),
]
assert len(T) == 48
